import type { ChangeEvent, Dispatch, MouseEvent, RefObject, SetStateAction } from 'react';
import type { ProxyCatalogDescriptor } from '@/lib/proxyCatalog';
import type { RatingPreference } from '@/lib/ratingPreferences';
import type { RatingProviderRow } from '@/lib/ratingRows';
import type { SupportedLanguage } from '@/lib/tmdbLanguage';
import type { BackdropRatingLayout } from '@/lib/backdropRatingLayout';
import type { ThumbnailRatingLayout } from '@/lib/thumbnailRatingLayout';
import type { ThumbnailSize } from '@/lib/thumbnailSize';
import type { BackdropRatingsSize } from '@/lib/backdropRatingsSize';
import type { PosterRatingLayout } from '@/lib/posterRatingLayout';
import type { RatingStyle } from '@/lib/ratingStyle';
import type { LogoMode } from '@/lib/logoMode';
import type { LogoFontVariant } from '@/lib/logoFontVariant';
import type { PosterGenrePosition, RankingPosition } from '@/lib/ratingBadgeLogic';

export type PreviewType = 'poster' | 'backdrop' | 'logo' | 'thumbnail';
export type ProxyType = PreviewType;
export type ProxyEnabledTypes = Record<ProxyType, boolean>;
export type StreamBadgesSetting = 'auto' | 'on' | 'off';
export type QualityBadgesSide = 'left' | 'right';
export type PosterQualityBadgesPosition = 'auto' | QualityBadgesSide;
export type { PosterGenrePosition, RankingPosition };
export type PosterConfiguratorPreset = 'simple' | 'advanced';
export type AiometadataPatternType = 'poster' | 'background' | 'logo' | 'episodeThumbnail';
export type AiometadataEpisodeProvider = 'tvdb' | 'realimdb';
export type ProxySeriesMetadataProvider = 'tmdb' | 'imdb';
export type ProxyEpisodeProvider = 'custom' | 'realimdb' | 'tvdb';
export type VerticalBadgeContent = 'standard' | 'stacked';

export type HomePageViewState = {
  previewType: PreviewType;
  mediaId: string;
  lang: string;
  posterLang: string;
  posterAnimeLang: string;
  backdropLang: string;
  backdropAnimeLang: string;
  logoLang: string;
  logoAnimeLang: string;
  posterAnimeImageText: 'default' | 'clean' | 'alternative';
  backdropAnimeImageText: 'default' | 'clean' | 'alternative';
  supportedLanguages: SupportedLanguage[];
  tmdbKey: string;
  mdblistKey: string;
  simklClientId: string;
  fanartKey: string;
  proxyManifestUrl: string;
  proxyCatalogs: ProxyCatalogDescriptor[];
  proxyCatalogNames: Record<string, string>;
  proxyHiddenCatalogs: string[];
  proxySearchDisabledCatalogs: string[];
  proxyDiscoverOnlyCatalogs: Record<string, boolean>;
  proxyCatalogsStatus: 'idle' | 'loading' | 'ready' | 'error';
  proxyCatalogsError: string;
  proxySeriesMetadataProvider: ProxySeriesMetadataProvider;
  proxyAiometadataProvider: ProxyEpisodeProvider;
  proxyEnabledTypes: ProxyEnabledTypes;
  proxyTranslateMeta: boolean;
  exportStatus: 'idle' | 'with' | 'without';
  importStatus: 'idle' | 'success' | 'error';
  importMessage: string;
  posterRatingsLayout: PosterRatingLayout;
  posterRatingsMaxPerSide: number | null;
  logoRatingsMax: number | null;
  logoMode: LogoMode;
  logoFontVariant: LogoFontVariant;
  logoCustomPrimary: string;
  logoCustomSecondary: string;
  logoCustomOutline: string;
  backdropRatingsLayout: BackdropRatingLayout;
  backdropRatingsMax: number | null;
  backdropRatingsSize: BackdropRatingsSize;
  thumbnailRatingsLayout: ThumbnailRatingLayout;
  posterVerticalBadgeContent: VerticalBadgeContent;
  backdropVerticalBadgeContent: VerticalBadgeContent;
  thumbnailVerticalBadgeContent: VerticalBadgeContent;
  thumbnailSize: ThumbnailSize;
  posterConfiguratorPreset: PosterConfiguratorPreset;
  posterAverageRatingsEnabled: boolean;
  posterVignetteEnabled: boolean;
  posterGenrePosition: PosterGenrePosition;
  posterSimpleRatingSource: 'average' | RatingPreference;
  qualityBadgesSide: QualityBadgesSide;
  posterQualityBadgesPosition: PosterQualityBadgesPosition;
  proxyCopied: boolean;
  copied: boolean;
  aiometadataCopiedType: AiometadataPatternType | null;
  aiometadataEpisodeProvider: AiometadataEpisodeProvider;
  activeToken: string | null;
  configSaveStatus: 'idle' | 'saving' | 'saved' | 'error';
  ranking: string;
  rankingCountry: string;
  rankingNoBox: boolean;
  rankingPosition: RankingPosition;
};

export type HomePageViewDerived = {
  baseUrl: string;
  previewUrl: string;
  proxyUrl: string;
  stremioInstallUrl: string;
  currentVersion: string;
  githubPackageVersion: string | null;
  repoUrl: string | null;
  previewNotice: string | null;
  canGenerateProxy: boolean;
  isProxyUrlVisible: boolean;
  displayedProxyUrl: string;
  styleLabel: string;
  textLabel: string;
  providersLabel: string;
  activeRatingStyle: RatingStyle;
  activeImageText: 'default' | 'clean' | 'alternative';
  ratingProviderRows: RatingProviderRow[];
  shouldShowQualityBadgesPosition: boolean;
  shouldShowQualityBadgesSide: boolean;
  qualityBadgeTypeLabel: string;
  activeStreamBadges: StreamBadgesSetting;
  activeQualityBadgesStyle: RatingStyle;
  aiometadataPatterns: Record<AiometadataPatternType, string>;
};

export type HomePageViewActions = {
  handleAnchorClick: (event: MouseEvent<HTMLAnchorElement>) => void;
  handleExportConfig: (includeKeys: boolean) => void;
  handleImportFile: (event: ChangeEvent<HTMLInputElement>) => void;
  handleImportConfigString: (value: string) => void;
  handleCopyProxy: () => void;
  handleCopyPrompt: () => void;
  handleCopyAiometadataPattern: (type: AiometadataPatternType) => void;
  setPreviewType: Dispatch<SetStateAction<PreviewType>>;
  setMediaId: Dispatch<SetStateAction<string>>;
  setLang: Dispatch<SetStateAction<string>>;
  setPosterLang: Dispatch<SetStateAction<string>>;
  setPosterAnimeLang: Dispatch<SetStateAction<string>>;
  setBackdropLang: Dispatch<SetStateAction<string>>;
  setBackdropAnimeLang: Dispatch<SetStateAction<string>>;
  setLogoLang: Dispatch<SetStateAction<string>>;
  setLogoAnimeLang: Dispatch<SetStateAction<string>>;
  setPosterAnimeImageText: Dispatch<SetStateAction<'default' | 'clean' | 'alternative'>>;
  setBackdropAnimeImageText: Dispatch<SetStateAction<'default' | 'clean' | 'alternative'>>;
  setTmdbKey: Dispatch<SetStateAction<string>>;
  setMdblistKey: Dispatch<SetStateAction<string>>;
  setSimklClientId: Dispatch<SetStateAction<string>>;
  setFanartKey: Dispatch<SetStateAction<string>>;
  setPosterRatingsLayout: Dispatch<SetStateAction<PosterRatingLayout>>;
  setPosterRatingsMaxPerSide: Dispatch<SetStateAction<number | null>>;
  setLogoRatingsMax: Dispatch<SetStateAction<number | null>>;
  setLogoMode: Dispatch<SetStateAction<LogoMode>>;
  setLogoFontVariant: Dispatch<SetStateAction<LogoFontVariant>>;
  setLogoCustomPrimary: Dispatch<SetStateAction<string>>;
  setLogoCustomSecondary: Dispatch<SetStateAction<string>>;
  setLogoCustomOutline: Dispatch<SetStateAction<string>>;
  setBackdropRatingsLayout: Dispatch<SetStateAction<BackdropRatingLayout>>;
  setBackdropRatingsMax: Dispatch<SetStateAction<number | null>>;
  setBackdropRatingsSize: Dispatch<SetStateAction<BackdropRatingsSize>>;
  setThumbnailRatingsLayout: Dispatch<SetStateAction<ThumbnailRatingLayout>>;
  setPosterVerticalBadgeContent: Dispatch<SetStateAction<VerticalBadgeContent>>;
  setBackdropVerticalBadgeContent: Dispatch<SetStateAction<VerticalBadgeContent>>;
  setThumbnailVerticalBadgeContent: Dispatch<SetStateAction<VerticalBadgeContent>>;
  setThumbnailSize: Dispatch<SetStateAction<ThumbnailSize>>;
  setPosterConfiguratorPreset: (value: PosterConfiguratorPreset) => void;
  setPosterAverageRatingsEnabled: Dispatch<SetStateAction<boolean>>;
  setPosterVignetteEnabled: Dispatch<SetStateAction<boolean>>;
  setPosterGenrePosition: Dispatch<SetStateAction<PosterGenrePosition>>;
  setPosterSimpleRatingSource: Dispatch<SetStateAction<'average' | RatingPreference>>;
  setAiometadataEpisodeProvider: Dispatch<SetStateAction<AiometadataEpisodeProvider>>;
  setProxySeriesMetadataProvider: Dispatch<SetStateAction<ProxySeriesMetadataProvider>>;
  setProxyAiometadataProvider: Dispatch<SetStateAction<ProxyEpisodeProvider>>;
  setPosterQualityBadgesPosition: Dispatch<SetStateAction<PosterQualityBadgesPosition>>;
  setQualityBadgesSide: Dispatch<SetStateAction<QualityBadgesSide>>;
  setRatingStyleForType: (value: RatingStyle) => void;
  setImageTextForType: (value: 'default' | 'clean' | 'alternative') => void;
  setActiveStreamBadges: Dispatch<SetStateAction<StreamBadgesSetting>>;
  setActiveQualityBadgesStyle: Dispatch<SetStateAction<RatingStyle>>;
  toggleRatingPreference: (rating: RatingPreference) => void;
  enableAllRatingPreferences: () => void;
  disableAllRatingPreferences: () => void;
  reorderRatingPreference: (fromIndex: number, toIndex: number) => void;
  updateProxyManifestUrl: (value: string) => void;
  updateProxyCatalogName: (key: string, value: string) => void;
  toggleProxyCatalogHidden: (key: string) => void;
  toggleProxyCatalogSearchDisabled: (key: string) => void;
  setProxyCatalogDiscoverOnly: (key: string, enabled: boolean) => void;
  resetProxyCatalogNames: () => void;
  resetProxyCatalogCustomizations: () => void;
  toggleProxyEnabledType: (type: ProxyType) => void;
  toggleProxyTranslateMeta: () => void;
  toggleProxyUrlVisibility: () => void;
  handleTokenDisconnect: () => void;
  handleSaveConfig: () => void;
  setRanking: Dispatch<SetStateAction<string>>;
  setRankingCountry: Dispatch<SetStateAction<string>>;
  setRankingNoBox: Dispatch<SetStateAction<boolean>>;
  setRankingPosition: Dispatch<SetStateAction<RankingPosition>>;
};

export type HomePageViewProps = {
  mode?: 'landing' | 'workspace';
  refs: {
    navRef: RefObject<HTMLElement | null>;
  };
  state: HomePageViewState;
  derived: HomePageViewDerived;
  actions: HomePageViewActions;
};
